---
title: "readme"
author: "Peter Searle"
date: "2024-05-14"
output: html_document
---

# Data

Description: 

data/assembly/cd-hit/transcriptomes - Final assembled transcriptomes used for phylogenetic analyses
  BearRiver.fasta.gz
  BeaverCR.fasta.gz
  BobtailCR.fasta.gz
  Bonneville1.fasta.gz
  Bonneville2.fasta.gz
  Coastal.fasta.gz
  Greenback.fasta.gz
  Humboldt.fasta.gz
  Lahontan.fasta.gz
  LWFBlackCR.fasta.gz
  RioGrande.fasta.gz
  UMCR.fasta.gz
  Westslope.fasta.gz
  Yellowstone.fasta.gz
  ncbi_files.tsv -  Information to match TSA files with original file names used in code. 
  
data/phylogeny - Final concatenated and coalescent-based species trees
  17sp_13_concat.tre - Concatenated species tree generated with genes with 13 or more specimens represented
  17sp_13_coalescent.tre - Coalescent species tree generated with genes with 13 or more specimens represented
  17sp_8_concat.tre - Concatenated species tree generated with genes with 8 or more specimens represented
  17sp_8_coalescent.tre - Coalescent species tree generated with genes with 8 or more specimens represented
  17sp_4_concat.tre - Concatenated species tree generated with genes with 4 or more specimens represented
  17sp_4_coalescent.tre - Coalescent species tree generated with genes with 4 or more specimens represented

data/raw/ncbi - Information to match raw SRA files with original file names used in code.
  ncbi_files.tsv - Note that the .bam files used for the transcriptome assembly are already demultiplexed because NCBI requested I provide those files, not the original movieX.subreads.bam file (which included samples multiplexed on the same run). You can run the transcriptome assembly code using IsoSeq3 starting at the "Refine" step.
  

  
  
